#!/usr/bin/env bash
#scripts comment
if [ "$#" -lt 4 ];
then
    printf "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\n"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
