#!/usr/bin/env bash
#commenting this script
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx restart
sudo rm -f /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
