#!/usr/bin/env bash
#comment this script
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i '/server_name _.*/a  \\trewrite ^/redirect_me\/$ https://www.linkedin.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
