#!/usr/bin/env bash
#comment this script
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i '/server_name _.*/a  \\trewrite ^/redirect_me\/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
