#!/usr/bin/env bash
#commenting this script
sudo apt-get update
sudo apt install haproxy=2.0.\*
sudo echo -e "\n\nfrontend nachogarcia.tech\n\tbind *:80\n\tdefault_backend http_back\n" >> /etc/haproxy/haproxy.cfg
sudo echo -e "backend http_back\n\tbalance roundrobin\n\tserver 3947-web-01 34.139.107.133:80 check\n\tserver 3947-web-02 35.196.253.16:80 check" >> /etc/haproxy/haproxy.cfg
sudo echo -e "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
