#!/usr/bin/env bash
#commenting this script
sudo apt-get update
sudo apt install haproxy=2.0.\*
sudo echo -e "\n\nfrontend http_front\n\tbind *:80\n\tdefault_backend http_back\n" >> /etc/haproxy/haproxy.cfg
sudo echo -e "backend http_back\n\tbalance roundrobin\n\tserver 3957-web-01 3.91.160.31:80\n\tserver 3957-web-02 54.160.189.223:80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "ENABLED=1" >> etc/default/haproxy
sudo service haproxy restart
