#!/usr/bin/env bash
#displays numbers from 1 to 100.
#Requirements:
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
for number in {1..100}
do
    if [ $((number % 3)) -eq 0 ]
    then
        echo -n "Fizz"
    fi
    if [ $((number % 5)) -eq 0 ]
    then
        echo -n "Buzz"
    elif [ $((number % 3)) -ne 0 ]
    then
        echo -n "$number"
    fi
    echo ""
done
