#!/usr/bin/env bash
#Prints "Best School" 10 times,
#but for the 9th iteration, displays Best School and then Hi on a new line.
#Requirements:
#Must use the while loop(for and until are forbidden)
#must use the if statement
times=1
while [ $times -lt 10 ]
do
    echo "Best School"
    ((times++))
    if [ $times -eq 9 ]
    then
        echo "Hi"
    fi
done
