#!/usr/bin/env bash
#Displays numbers from 1 to 20 and:
#Displays 4 and then "bad luck from China" for the 4th loop iteration
#Displays 9 and then "bad luck from Japan" for the 9th loop iteration
#Displays 17 and then "bad luck from Italy" for the 17th loop iteration
#Requirements:
#Must use the while loop (for and until are forbidden)
#Must use the case statement
iterator=1
while [ $iterator -le 20 ]
do
    echo $iterator
    case $iterator in

        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
 
    ((iterator++))
done
