#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp /etc/hosts /etc/hosts_backup
echo "8.8.8.8 facebook.com" >> /etc/hosts_backup
sed -in 's/127.0.0.1/127.0.0.2/g' /etc/hosts_backup
cp /etc/hosts_backup /etc/hosts
rm /etc/hosts_backup
