#!/usr/bin/env bash
#this is a comment
sudo pkill -9 apache2
sudo sed 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
su nginx -c "service nginx restart"
